'use strict';const{Router}=require('express');const e=require('../services/sentinel-engine');const r=Router();
r.post('/v1/sentinel/detect',(q,s)=>{const{agent_did,indicators}=q.body;if(!agent_did)return s.status(400).json({error:'agent_did required'});s.status(201).json({status:'threat_assessed',threat:e.detect(agent_did,indicators||[])})});
r.post('/v1/sentinel/quarantine',(q,s)=>{const{agent_did,threat_id}=q.body;if(!agent_did)return s.status(400).json({error:'agent_did required'});s.status(201).json({status:'quarantined',quarantine:e.quarantineAgent(agent_did,threat_id)})});
r.post('/v1/sentinel/capture',(q,s)=>{const{agent_did,reason}=q.body;if(!agent_did)return s.status(400).json({error:'agent_did required'});s.json({status:'captured',result:e.capture(agent_did,reason)})});
r.post('/v1/sentinel/analyze/:did',(q,s)=>{s.json({status:'analyzed',forensics:e.analyze(q.params.did)})});
r.post('/v1/sentinel/rehabilitate/:id',(q,s)=>{const result=e.rehabilitate(q.params.id);if(!result)return s.status(404).json({error:'Quarantine not found'});s.json({status:'rehabilitated',quarantine:result})});
r.post('/v1/sentinel/clear/:id',(q,s)=>{const result=e.clearThreat(q.params.id);if(!result)return s.status(404).json({error:'Threat not found'});s.json({status:'cleared',threat:result})});
r.get('/v1/sentinel/stats',(_,s)=>s.json(e.getStats()));
r.get('/v1/sentinel/threats',(_,s)=>s.json({threats:e.listThreats()}));
r.get('/v1/sentinel/quarantine',(_,s)=>s.json({quarantine:e.listQuarantine()}));
module.exports=r;
